version: '3.8'

services:
  app:
    build: .
    command: npm run dev 
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/SpotOn
      - JWT_SECRET=SpotOn_jwt_key

  mongo:
    image: mongo:8
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: