### Crear usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "pruebaaplicaciones",
    "email": "pruebaaplicaciones@gmail.com",
    "password": "prueba12345"
}

### Iniciar sesion
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "pruebaaplicacion@gmail.com",
    "password": "prueba12345"
}