### Crear usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "lautaroespil",
    "email": "espilcrespo@gmail.com",
    "password": "contra123"
}

### Iniciar sesion
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "espilcrespo@gmail.com",
    "password": "contra123"
}