### Crear usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Gomez",
    "email": "marcos@gmail.com",
    "password": "123456"
}

### Obtener usuarios
GET http://localhost:3000/api/users

### Obtener usuario por id
GET http://localhost:3000/api/users/6a253c4ecdddbbd74d30956c

### Actualizar usuario
PUT http://localhost:3000/api/users/6a253c4ecdddbbd74d30956c
Content-Type: application/json

{
    "name": "Gomez",
    "email": "Gomez@gmail.com"
}

### Eliminar usuario
DELETE http://localhost:3000/api/users/6a253c4ecdddbbd74d30956c
