### Crear usuario
POST http://localhost:3000/user/post
Content-Type: application/json

{
    "name": "UsuarioGenerico1",
    "email": "Generico1@gmail.com",
    "password": "1234567"
}

### Obtener usuarios
GET http://localhost:3000/user/get

### Obtener usuario por id
GET http://localhost:3000/user/getById/6a296eedf4d25025a6b46472

### Actualizar usuario
PUT http://localhost:3000/user/update/6a2c9a2acba4cf99ef2f11fa
Content-Type: application/json

{
    "name": "Usuario",
    "email": "Usuario@gmail.com"
}

### Eliminar usuario
DELETE http://localhost:3000/user/delete/6a253c4ecdddbbd74d30956c
