### Crear usuario
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "UsuarioGenerico",
    "email": "Generico@gmail.com",
    "password": "123456"
}

### Obtener usuarios
GET http://localhost:3000/api/users

### Obtener usuario por id
GET http://localhost:3000/api/users/6a253c4ecdddbbd74d30956c

### Actualizar usuario
PUT http://localhost:3000/api/users/6a2c9a2acba4cf99ef2f11fa
Content-Type: application/json

{
    "name": "Usuario",
    "email": "Usuario@gmail.com"
}

### Eliminar usuario
DELETE http://localhost:3000/api/users/6a253c4ecdddbbd74d30956c
